### ISSUE TITLE
Where i can get client game ?

### ISSUE THREAD

**Issue by zababurinsv** [DVDAGames/elite-dangerous-journal-server#50]
Maybe this question is not for you.

Where can I get the game itself for this server?
Is there a client written in js ?

**Comment by ericrallen** [comment]
@zababurinsv Hey there, I didn't see the notification for this one come through.

The game, Elite Dangerous, is a PC Game (it's on other platforms, too, but they won't work with this utility) available from Frontier: https://www.elitedangerous.com/
